version: '3.8'

services:
  app:
    build: .
    container_name: baozi-panda-backend
    ports:
      - "3009:3009"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    name: baozi-panda-backend_default